/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AddWordRouteImport } from './routes/add-word'

const AddWordRoute = AddWordRouteImport.update({
  id: '/add-word',
  path: '/add-word',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/add-word': typeof AddWordRoute
}
export interface FileRoutesByTo {
  '/add-word': typeof AddWordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/add-word': typeof AddWordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/add-word'
  fileRoutesByTo: FileRoutesByTo
  to: '/add-word'
  id: '__root__' | '/add-word'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AddWordRoute: typeof AddWordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/add-word': {
      id: '/add-word'
      path: '/add-word'
      fullPath: '/add-word'
      preLoaderRoute: typeof AddWordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AddWordRoute: AddWordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
