name: Deploy Scheduled Google Cloud Job

on:
  push:
    branches:
      - main
    paths:
      - 'server/src/jobs/**'
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west1 
  REPO_NAME: pt-revise-word
  IMAGE_NAME: notify-due-words
  SERVICE_NAME: notify-due-words
  SERVER_PATH: server/

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }} 

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy Cloud Run Job
        run: |
          gcloud run jobs deploy ${{ env.SERVICE_NAME }} \
            --source ${{ env.SERVER_PATH }} \
            --region ${{ env.REGION }} \
            --set-env-vars="PINO_LOG_LEVEL=info" \
            --max-retries 3
